### ISSUE TITLE
Add ReadOnly states to all form components.

### ISSUE THREAD

**Issue by Akshat55** [carbon-design-system/carbon-components-angular#2893]
This issue is an epic for ReadOnly state!

```[tasklist]
### Tasks
- [ ] https://github.com/carbon-design-system/carbon-components-angular/issues/2894
- [ ] https://github.com/carbon-design-system/carbon-components-angular/issues/2895
- [ ] https://github.com/carbon-design-system/carbon-components-angular/issues/2896
- [ ] https://github.com/carbon-design-system/carbon-components-angular/issues/2897
- [ ] https://github.com/carbon-design-system/carbon-components-angular/issues/2898
- [ ] https://github.com/carbon-design-system/carbon-components-angular/issues/2899
- [ ] https://github.com/carbon-design-system/carbon-components-angular/issues/2900
- [ ] https://github.com/carbon-design-system/carbon-components-angular/issues/2901
```

Ex output (Select):
![image](https://github.com/carbon-design-system/carbon-components-angular/assets/38994122/a65115fb-039a-4170-a718-fdea579fbcce)

**Comment by Akshat55** [comment]
Closing EPIC as all readonly states have been added!
